name: ⭐ Language Argument
description: Want to advocate for a language? Do it here.
labels: [ language,under review ]
body:
  - type: dropdown
    id: language
    attributes:
      label: 🚀 Which language is better?
      description: We all know C# is, clearly, but what do you think it is?
      options:
        - 🔥 C#
        - 💩 JavaScript
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🤔 What's your case against the opposition?
      description: Help us understand why it's better (and yes, "because I said so" is valid).
    validations:
      required: true